FROM elixir:1.14-alpine as builder

ENV MIX_ENV=prod

WORKDIR /app

RUN apk add --no-cache --update git build-base ca-certificates zstd

RUN mkdir config
COPY config/ ./config
COPY . .
COPY mix.exs .
COPY mix.lock .

RUN mix local.rebar --force \
    && mix local.hex --force \
    && mix deps.get \
    && mix deps.get \
    && mix release.init

RUN echo "-name activator_pubsub@${HOSTNAME}" >> ./rel/vm.args.eex \
    && echo "-setcookie ${NODE_COOKIE}" >> ./rel/vm.args.eex

RUN MIX_ENV=prod mix release activator_pubsub

# ---- Application Stage ----
FROM alpine:3
#RUN apk add --no-cache --update bash openssl build-base ca-certificates zstd
RUN apk add --no-cache --update zstd ncurses-libs libstdc++ libgcc

WORKDIR /home/app
COPY --from=builder /app/_build/prod/rel/bakeware .

RUN adduser app --disabled-password --home app
RUN chown -R app: /home/app
USER app
RUN mkdir -p app/.cache/bakeware

ENV MIX_ENV=prod

ENTRYPOINT ["./activator_pubsub", "start"]