FROM elixir:1.14-alpine as builder

ENV MIX_ENV=prod

WORKDIR /app

RUN apk add --no-cache --update git build-base ca-certificates zstd

RUN mkdir config
COPY config/ ./config
COPY spawn_sdk/ ./spawn_sdk
COPY apps/ ./apps
COPY mix.exs .
COPY mix.lock .

RUN mix local.rebar --force \
    && mix local.hex --force \
    && mix deps.get \
    && mix release.init

RUN echo "-name spawn_sdk_elixir@${HOSTNAME}" >> ./rel/vm.args.eex \
    && echo "-setcookie ${NODE_COOKIE}" >> ./rel/vm.args.eex

RUN cd spawn_sdk/spawn_sdk_example \
    && mix deps.get \
    && mix release spawn_sdk_example

# ---- Application Stage ----
FROM alpine:3
RUN apk add --no-cache --update zstd ncurses-libs libstdc++ libgcc

WORKDIR /home/app
COPY --from=builder /app/_build/prod/rel/bakeware .

RUN adduser app --disabled-password --home app
RUN chown -R app: /home/app
USER app
RUN mkdir -p app/.cache/bakeware

ENV MIX_ENV=prod

RUN ls -ltra

ENTRYPOINT ["./spawn_sdk_example", "start"]
