FROM elixir:1.15-alpine as builder

ENV MIX_ENV=prod

WORKDIR /app

RUN apk add --no-cache --update git build-base ca-certificates zstd gcc pkgconfig openssl-dev

COPY spawn_initializer/ .

RUN mix local.rebar --force \
    && mix local.hex --force \
    && mix deps.get \
    && mix release.init

# Overriden at runtime
ENV POD_IP="127.0.0.1"

# This will be the basename of node
ENV RELEASE_NAME="spawn_initializer"

# This will be the full nodename
ENV RELEASE_NODE="${RELEASE_NAME}@${POD_IP}"


RUN mix deps.get \
    && mix release spawn_initializer

# ---- Application Stage ----
FROM alpine:3.19.1

RUN apk add --no-cache --update zstd ncurses-libs libstdc++ libgcc

WORKDIR /app
RUN chown nobody /app

# Set runner ENV
ENV MIX_ENV=prod
ENV HOME=/app

COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/bakeware/ ./

RUN mkdir -p /app/.cache/bakeware/ && chmod 777 /app/.cache/bakeware/
RUN touch /.erlang.cookie && chmod 777 /.erlang.cookie
RUN touch /app/.erlang.cookie && chmod 777 /app/.erlang.cookie

USER nobody

ENTRYPOINT ["./spawn_initializer"]
