FROM elixir:1.14-alpine as builder

ENV MIX_ENV=prod

WORKDIR /app

RUN apk add --no-cache --update git build-base ca-certificates zstd

RUN mkdir config
COPY config/ ./config
COPY spawn_activators/activator_http/ ./spawn_activators/activator_http
COPY lib/ ./lib
COPY priv/ ./priv
COPY mix.exs .
COPY mix.lock .

RUN mix local.rebar --force \
    && mix local.hex --force \
    && mix deps.get \
    && mix release.init \
    && mix rewrite_versions --apps=spawn

ENV RELEASE_DISTRIBUTION="name"

# Overriden at runtime
ENV POD_IP="127.0.0.1"

# This will be the basename of node
ENV RELEASE_NAME="activator_http"

# This will be the full nodename
ENV RELEASE_NODE="${RELEASE_NAME}@${POD_IP}"

RUN echo "-setcookie ${NODE_COOKIE}" >> ./rel/vm.args.eex

RUN cd spawn_activators/activator_http \
    && mix deps.get \
    && mix release activator_http

# ---- Application Stage ----
FROM alpine:3.17.3
#RUN apk add --no-cache --update bash openssl build-base ca-certificates zstd
RUN apk add --no-cache --update zstd ncurses-libs libstdc++ libgcc

WORKDIR /app
RUN chown nobody /app

# Set runner ENV
ENV MIX_ENV=prod
ENV HOME=/app

COPY --from=builder --chown=nobody:root /app/_build/${MIX_ENV}/rel/bakeware/ ./

RUN mkdir -p /app/.cache/bakeware/ && chmod 777 /app/.cache/bakeware/
RUN touch /.erlang.cookie && chmod 777 /.erlang.cookie
RUN touch /app/.erlang.cookie && chmod 777 /app/.erlang.cookie

USER nobody

ENTRYPOINT ["./activator_http", "start"]