FROM elixir:1.14-alpine as builder

ENV MIX_ENV=prod

WORKDIR /app

RUN apk add --no-cache --update git build-base ca-certificates zstd

RUN mkdir config
COPY config/ ./config
COPY spawn_operator/ ./spawn_operator
COPY lib/ ./lib
COPY mix.exs .
COPY mix.lock .

RUN mix local.rebar --force \
    && mix local.hex --force \
    && mix deps.get \
    && mix release.init

RUN echo "-name spawn_operator@${HOSTNAME}" >> ./rel/vm.args.eex \
    && echo "-setcookie ${NODE_COOKIE}" >> ./rel/vm.args.eex

RUN cd spawn_operator/spawn_operator \
    && mix deps.get \
    && mix release spawn_operator

# ---- Application Stage ----
FROM alpine:3

RUN apk add --no-cache --update zstd ncurses-libs libstdc++ libgcc

WORKDIR /home/app
COPY --from=builder /app/_build/prod/rel/bakeware/spawn_operator .

RUN adduser app --disabled-password --home app
RUN mkdir -p app/.cache/bakeware
RUN chown -R app: /home/app

RUN touch /.erlang.cookie && chmod 777 /.erlang.cookie
RUN touch /home/app/.erlang.cookie && chmod 777 /home/app/.erlang.cookie

USER app

ENV MIX_ENV=prod

ENTRYPOINT ["./spawn_operator", "start"]